language: node_js
services: mysql
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- npm run test
- npm run cover
- npm run report
env:
  global:
    secure: V3j9a/SiPnpG7YEMtBW+JJADimB+w+3eLzxLtVONO2coNHezou8/srNMGVMJhMfIBXDS2HykbmFQivDhDcGmDXG2xp2x6t5I5yPESNR8mnCDYEdYlo7Ar1vEgWeB/6Xz1kbzlBmPHzSrsUja46gbsjCpv+B7wbkhsp9RX8vl3NzaU9YNPksGArisrctwd4IPEa7vcQ9+AYt3L/a2MIYtkG7XNKTBTWj03Tq815p9dQFBRrm+bxzx8spWKqCRaKaedVT2fkwdRDVq+OQapG2Q0FZ8CZtrF+QKVK2Hxn7PwzgQzPoY6bcY4MrQ6PfQzQGIrxYB6o4bL8AvqkrggNJw64lTOzcSq7sjnH021miqFJ8xS7zolyUFkGuUaX9rguwTQpQf3wL488SH61g9FbuNbG7jgInNyUDfvJR0jmg/wBsnlK55fKskyLOc+Y1PiCfRP0KbnImdPZPll+pwhSHnrEsS6e5T8TN08SmpJzAd9eY7gshvMRZYy5pCTfSBbE7hTjE4JI7hrEmC4KPLHfK9Y3tWUmvcIWprAniZYkdvDr3te/YVLYQQ61IQQKf+B+80QPXCRqvbDuLK+oltlKh0CQWYcuB6+SeN5+Q+6teYkLsP8i1z0cAPbuWesPpzmjnt0L8aTwksQWN6/PnaACEBZTfhEg2N05Oe1zAGtvqq9gI=
